### ISSUE TITLE
'Sloped fenders' don't mirror properly 

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#210]
The sloped fender type doesn't mirror properly, both generated fenders and placeable parts are affected.

![image](https://user-images.githubusercontent.com/109303520/201388918-477f4fc8-8fd7-4036-9d41-6b1d366fd1b2.png)

**Comment by Muushy** [comment]
Fixed in V0.1249

**Comment by DarioXN** [comment]
Still present in 0.12410

![image](https://user-images.githubusercontent.com/109303520/204161612-0697e948-828a-43d4-b10d-ea19a8393dd9.png)

**Comment by Muushy** [comment]
Fixed in V0.12415
