### ISSUE TITLE
Excessive expansion ratios cause excessive velocity

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#257]
Title.

Can go over 40.000m/s

**Comment by Muushy** [comment]
Fixed in V0.12415

**Comment by DarioXN** [comment]
Bug is still present in 0.12417 and earlier versions

It is caused by long barrels with short propellant lengths, limiting propellant length to 1x caliber doesn't seem to help much.

**Comment by Muushy** [comment]
Clamped expansion ratio in V0.12418
