### ISSUE TITLE
Unable to open Custom Battle menu

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#310]
Title, this happens if for example, the battle is set to 24 tanks on one side, and then the map get's changed to one that doesn't support 24 tanks on one side, after this, the menu cannot be opened, even after restarting, the only way to get it to work again is to delete the custom battle setup json file.

**Comment by Muushy** [comment]
Fixed in V0.12422.

**Comment by DarioXN** [comment]
Still happens to some users
Might need to set it up so that the custom battle setup file gets deleted or overwritten if the menu fails to open

**Comment by Muushy** [comment]
Exception handling improved in V0.12423.
Auto-save file will be deleted when an exception is encountered.

**Comment by DarioXN** [comment]
Haven't had any complaints about this one is quite a while, I think it's safe to consider it fixed.

**Comment by Muushy** [comment]
Further improved the stability in V0.1252, should be OK now.

**Comment by DarioXN** [comment]
After a long pause, this one seems to have returned recently.

**Comment by COFFEE992** [comment]
It happened to me today. I tried to launch a custom battle and it wouldn't open at all. The screen would flash once for a split second and nothing else would happen. All the other options still work though...

**Comment by COFFEE992** [comment]
> Further improved the stability in V0.1252, should be OK now.
It happened to me today. I tried to launch a custom battle and it wouldn't open at all. The screen would flash once for a split second and nothing else would happen. All the other options still work though...

**Comment by COFFEE992** [comment]
> Further improved the stability in V0.1252, should be OK now.



It happened to me today. I tried to launch a custom battle and it wouldn't open at all. The screen would flash once for a split second and nothing else would happen. All the other options still work though...

**Comment by Commissar0617** [comment]
yep, same.

**Comment by Muushy** [comment]
Fixed in 0.2.23
