### ISSUE TITLE
Key rebinding not taking immediate effect

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#459]
Title, not a problem with the button but the control in general

**Comment by ColsonThePCMechanic** [comment]
Strangely I never noticed this issue myself.  Maybe it triggers in certain scenarios?

**Comment by DarioXN** [comment]
Correction, it seems to not listen to bound controls, I have it set to a different button and it does not work with it, additionally the hold aim lock setting does not do anything.

**Comment by DarioXN** [comment]
Correction 2, the hold aim lock setting seems to have taken effect after restarting the game

**Comment by Muushy** [comment]
Key rebinding don't seem to be taking immediate effect at the moment.

**Comment by DarioXN** [comment]
Addition, this seems to affect a lot of other settings

**Comment by Muushy** [comment]
Fixed in 0.2.26

**Comment by robotnikthingy** [comment]
@Muushy It looks like the problem is still there, reassigning keybinds does not work as before the patch. If you look in the bug-reports channel on the discord you can see others reporting it as well. I attached my settings.json with some keybinds changed if that helps

[Settings.json](https://github.com/user-attachments/files/18340665/Settings.json)

**Comment by Muushy** [comment]
Thanks, I'll take a look

**Comment by Muushy** [comment]
Fixed in 0.2.26.2
Was just a problem with the rebinding GUI not loading applied rebinds.

**Comment by robotnikthingy** [comment]
Thanks @Muushy . I hate to bring bad news, but it still does not seem to work. When you rebind a key, it shows the new key in options, but still does not do anything in game when you use the new key.

**Comment by Muushy** [comment]
Hmm, seems to be working ok on my machine.
@robotnikthingy Is this happening for you with every rebind? or just a few specific ones?

**Comment by robotnikthingy** [comment]
@Muushy The ones I've tried are Scope, Cruise Control, and Lock Aim
I'll try others tonight when I have some time.

**Comment by robotnikthingy** [comment]
@Muushy Sorry for the late response, I was busy with family. I went ahead and tried about half the keybinds, still the same result, the UI shows the key rebinded to the correct one, but nothing changes in game or the editor.

Let me know if there are any log files or other testing I can do to help with this issue.

**Comment by Muushy** [comment]
Looks like the issue was just with the vehicle controls
Should be fully working in 0.2.35.2

**Comment by robotnikthingy** [comment]
Did some testing and can confirm it is working now. Thank you!
