### ISSUE TITLE
Exhaust smoke separates into forwards and backwards plumes when moving

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#482]
Title, the forwards smoke should not be present.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/0bf15924-8641-4319-b3f2-f346c9f6d885)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B2

**Comment by DarioXN** [comment]
This one seems to still happen in the new version.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/16b7521e-b013-4225-b23a-bb52f21ba6dc)

**Comment by SprocketTools** [comment]
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/4545fcd8-2d08-4020-92a0-7e42534849ca)
Bug seems more prevalent when driving backwards.  Moving forwards, it is far less evident.

**Comment by Muushy** [comment]
Fixed in 0.2.6
