### ISSUE TITLE
Plates with perfectly aligned boundaries give wrong armor values

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#507]
Title, you already know this one.

A potential quick way to fix it could be to slightly fudge the collisions by adding an unlikely to naturally occur fraction of a millimeter (ex. 0.21mm) to what is counted so that the two plates overlap slightly.

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B4
Did the proper fix. Allowed damage model samples to collect all hit faces within a 10 micrometre range.

**Comment by DarioXN** [comment]
This one still happens in B4, but now if the plates overlap by 1mm (potentially other overlap amounts too).

**Comment by Muushy** [comment]
Fixed in 0.2.8
