### ISSUE TITLE
Unable to load specific tank in designer/custom battles

### ISSUE THREAD

**Issue by Ripard-A** [Muushy/Sprocket-Feedback#799]
**Describe the bug**
A specific tank design does not load in the designer, and if I try to use it in a custom scenario, the scenario never loads.

0.2.34.2

**To Reproduce**
1. Loaded faction
2. Click on 'Load Vehicle Blueprints'
3. Click on relevant design ''
4. Tank does not load, instead remaining on current design.

**Expected behavior**
When selecting the tank, it loads correctly.

**Screenshots**
Selecting tank from saved blueprints:
![Image](https://github.com/user-attachments/assets/0c41989b-bd01-410e-98d3-ac567f9dfaef)

Previously Loaded tank remains:

![Image](https://github.com/user-attachments/assets/f2d9071f-ef82-49c0-8875-53e443b9caff)

**Additional context**
I attempted to copy the file and rename it, both the file name and the design name using notepad, but there was no change.

I attempted to validate files, and then reinstalled the game, but no change.

**Comment by Muushy** [comment]
Thanks for the report!
Could you provide the problematic design? - Can't reproduce this otherwise.

**Comment by Ripard-A** [comment]
I'm not sure how to add the file to Github, so here's a google drive link:

https://drive.google.com/file/d/1j5LICWulSUwL2B6mYkRpEiGx8MOjJUvi/view?usp=sharing

**Comment by Muushy** [comment]
Thanks! I'll get that fixed

**Comment by Muushy** [comment]
Fixed in 0.2.41

**Comment by Ripard-A** [comment]
I just checked again, and the design still isn't loading for me. I tried deleting it from the original faction and downloading the file I sent to another, and it still isn't working. I confirmed, sprocket downloaded the update for me.

**Comment by Ripard-A** [comment]
I just realised, 0.2.41 would be the next update. Many thanks for the quick work, and hope all is well :)
